---
- name: install cockpit
  package:
    name: cockpit
    state: present
  become: yes

- name: enable cockpit
  service:
    name: cockpit.socket
    enabled: yes
    state: started
  become: yes

- name: install webpack globally
  npm:
    name: webpack
    global: yes
    path: /vagrant/subscription-manager/cockpit
  become: yes

- name: install cockpit packages
  npm:
    state: latest
    path: /vagrant/subscription-manager/cockpit
